"""Generated by the sketch-to-CAD drawing app.

Reconstructs the model that was on screen at save time. Tweak the parameters
at the top and re-run.
"""
import sys; sys.path.insert(0, "cad")
from _render import render
import cadquery as cq

# ---- Op 0: extrude 2 stroke(s) by 10.0mm on plane XY ----
H_OP_0 = 10.000   # mm — extrude height for this sketch

# Feature 1 (outer) — polygon (9 pts)
F1_PTS = [(-2.727272727272727, 29.999999999999996), (19.09090909090909, 24.545454545454543), (29.999999999999996, 2.727272727272727), (24.545454545454543, -19.09090909090909), (2.727272727272727, -29.999999999999996), (-19.09090909090909, -24.545454545454543), (-29.999999999999996, -2.727272727272727), (-21.818181818181817, 19.09090909090909), (-2.727272727272727, 29.999999999999996)]

# Feature 2 (hole) — rect
F2_CX = 0.000
F2_CY = -2.727
F2_W  = 10.909
F2_H  = 10.909

# ---- geometry --------------------------------------------------------------
result = cq.Workplane("XY").polyline(F1_PTS).close().extrude(H_OP_0)
_hole = cq.Workplane("XY").center(F2_CX, F2_CY).rect(F2_W, F2_H).extrude(H_OP_0 + 4).translate((0,0,-2))
result = result.cut(_hole)
result = result.edges(">Z").fillet(1.500)

render(result, "demo_save")