"""Generated by the sketch-to-CAD drawing app.

Reconstructs the model that was on screen at save time. Tweak the parameters
at the top and re-run.
"""
import sys; sys.path.insert(0, "cad")
from _render import render
import cadquery as cq

# ---- Op 0: extrude 4 stroke(s) by 45.0mm on plane=XY mode=new_body ----
H_OP_0 = 45.000

# Feature 1 (outer) — circle
F1_CX = -88.444
F1_CY = 88.889
F1_R  = 11.098

# Feature 2 (additive) — circle
F2_CX = 89.333
F2_CY = 88.889
F2_R  = 11.098

# Feature 3 (additive) — circle
F3_CX = 89.333
F3_CY = -88.889
F3_R  = 11.098

# Feature 4 (additive) — circle
F4_CX = -88.444
F4_CY = -88.889
F4_R  = 11.098

# ---- Op 1: extrude 1 stroke(s) by 4.0mm on plane=top mode=join ----
H_OP_1 = 4.000

# Feature 5 (outer) — rect
F5_CX = 0.000
F5_CY = 0.000
F5_W  = 200.000
F5_H  = 200.000

# ---- Op 2: extrude 1 stroke(s) by 40.0mm on plane=top mode=join ----
H_OP_2 = 40.000

# Feature 6 (outer) — rect
F6_CX = 0.000
F6_CY = 0.000
F6_W  = 200.000
F6_H  = 7.500

# ---- geometry --------------------------------------------------------------
Z_TOP = 0.0   # top Z of the current model (mm)
Z_BOT = 0.0   # bottom Z of the current model (mm)
# Op 0: sketch_extrude (mode=new_body, plane=XY)
_op_solid = cq.Workplane("XY").center(F1_CX, F1_CY).circle(F1_R).extrude(H_OP_0)
_op_solid = _op_solid.union(cq.Workplane("XY").center(F2_CX, F2_CY).circle(F2_R).extrude(H_OP_0))
_op_solid = _op_solid.union(cq.Workplane("XY").center(F3_CX, F3_CY).circle(F3_R).extrude(H_OP_0))
_op_solid = _op_solid.union(cq.Workplane("XY").center(F4_CX, F4_CY).circle(F4_R).extrude(H_OP_0))
result = _op_solid
Z_TOP += H_OP_0

# Op 1: sketch_extrude (mode=join, plane=top)
_op_solid = cq.Workplane("XY").center(F5_CX, F5_CY).rect(F5_W, F5_H).extrude(H_OP_1)
_op_solid = _op_solid.translate((0, 0, Z_TOP))
result = result.union(_op_solid)
Z_TOP += H_OP_1

# Op 2: sketch_extrude (mode=join, plane=top)
_op_solid = cq.Workplane("XY").center(F6_CX, F6_CY).rect(F6_W, F6_H).extrude(H_OP_2)
_op_solid = _op_solid.translate((0, 0, Z_TOP))
result = result.union(_op_solid)
Z_TOP += H_OP_2


render(result, "demo_chair")