"""Generated by the sketch-to-CAD drawing app on the fly."""
import sys; sys.path.insert(0, "cad")
from _render import render
import cadquery as cq

# ---- parameters (edit these to tweak) -----------------------------------------
EXTRUDE_HEIGHT = 10.000   # mm
# Feature 1: circle as outer
F1_OUTER_CX = 0.742
F1_OUTER_CY = 0.561
F1_OUTER_RADIUS = 29.431

# Feature 2: circle as hole
F2_HOLE_CX = -1.425
F2_HOLE_CY = -2.899
F2_HOLE_RADIUS = 12.023

# ---- geometry -----------------------------------------------------------------
result = cq.Workplane("XY").center(F1_OUTER_CX, F1_OUTER_CY).circle(F1_OUTER_RADIUS).extrude(EXTRUDE_HEIGHT)
_hole = (cq.Workplane("XY").center(F2_HOLE_CX, F2_HOLE_CY).circle(F2_HOLE_RADIUS).extrude(EXTRUDE_HEIGHT + 4).translate((0,0,-2)))
result = result.cut(_hole)

# ---- export + render ----------------------------------------------------------
render(result, "drawn_ring")
